# Generated by Django 5.1 on 2024-08-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_employeeprofile_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
