# Generated by Django 5.1 on 2024-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_employeeprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(blank=True, default='images/default/blank_company_logo.jpg', upload_to='images/companies_logos/'),
        ),
    ]
