# Generated by Django 5.1 on 2024-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(blank=True, default='images/default/blank_company_logo.png', upload_to='images/companies_logos/'),
        ),
    ]
