# Generated by Django 5.1 on 2024-09-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='close_reason',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Solved', 'Solved'), ('Unsolvable', 'Unsolvable')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
