# Generated by Django 5.1 on 2024-09-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_close_reason_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='close_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
