# Generated by Django 5.1 on 2024-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Medium'), (2, 'High'), (3, 'Critic')], default=0, max_length=10),
        ),
    ]
