# Generated by Django 5.1 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='static/images/default/blank_profile_picture.jpg', upload_to='static/images/users_profile_pictures/'),
        ),
    ]
